version: '3'

networks:
  monitoring:

services:
  prometheus:
    image: prom/prometheus:v2.44.0
    networks:
      - monitoring
    volumes:
      - prometheus:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter:v1.5.0
    networks:
      - monitoring
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana-oss:9.5.2
    networks:
      - monitoring
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  grafana:
  prometheus:
  proc:
  sys:
